bootstrap_blog/blogapp/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('ingreso/', views.ingreso, name='ingreso'),
    path('proveedor/', views.ingresoproveedor, name='proveedor'),
    path('login/', views.login, name='login'),
    path('logout/',views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
]

bootstrap_blog/bootstrap_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from blogapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('ingreso/', views.ingreso, name='ingreso'),
    path('proveedor/', views.ingresoproveedor, name='proveedor'),
    path('login/', views.login, name='login'),
    path('logout/',views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
]

urlpatterns += staticfiles_urlpatterns()

bootstrap_blog/blogapp/models.py
from django.db import models


# Create your models here.

class Cliente(models.Model):
    nombre=models.CharField(max_length=50)
    apellido=models.CharField(max_length=50)
    apellidoM=models.CharField(max_length=50)
    correo=models.EmailField(max_length=100)
    pais=models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre

class Proveedor(models.Model):
    razon_social=models.CharField(max_length=50)
    contacto=models.CharField(max_length=50)
    correo=models.EmailField(max_length=100)
    
    def __str__(self):
        return self.razon_social

bootstrap_blog/blogapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db.models import fields
from django.forms import ModelForm


class RegistroClienteForm(forms.Form):
    nombre=forms.CharField (max_length=50, required=True)
    apellido=forms.CharField (max_length=50, required=True)
    apellidoM=forms.CharField (max_length=50, required=True)
    correo=forms.CharField(widget=forms.EmailInput)
    pais=forms.CharField(max_length=50, required=True)

class RegistroProveedorForm(forms.Form):
    razon_social=forms.CharField (max_length=50, required=True)
    contacto=forms.CharField (max_length=50, required=True)
    correo=forms.CharField(widget=forms.EmailInput)

class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput)
    password=forms.CharField(widget=forms.PasswordInput)

class NewUserForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmar contraseña", widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}

bootstrap_blog/blogapp/views.py
from blogapp.models import Cliente

from django.shortcuts import redirect, render
from .models import Cliente, Proveedor
from .forms import RegistroClienteForm, RegistroProveedorForm
# from .forms import LoginForm, UserRegisterForm
from .forms import LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.defaults import page_not_found
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.admin.views.decorators import staff_member_required
from .forms import NewUserForm

# Create your views here.

def index(request):
    return render(request,"blogapp/index.html")

def usuarios(request):
    usuario=Cliente.objects.all()
    return render (request, 'blogapp/usuarios.html', {"data":usuario})

def ingreso(request):
    form = RegistroClienteForm()

    if request.method == 'POST':
        
        form = RegistroClienteForm(request.POST)

        if form.is_valid():

            cliente=Cliente()
            cliente.nombre=form.cleaned_data["nombre"]
            cliente.apellido=form.cleaned_data["apellido"]
            cliente.apellidoM=form.cleaned_data["apellidoM"]
            cliente.correo=form.cleaned_data["correo"]
            cliente.pais=form.cleaned_data["pais"]
            cliente.save()
            return redirect('ingreso')

        else:
            print('invalido')

    return render(request, 'blogapp/ingreso.html',{'form':form})

@staff_member_required
@login_required
def ingresoproveedor(request):
    form = RegistroProveedorForm()

    if request.method == 'POST':
        
        form = RegistroProveedorForm(request.POST)

        if form.is_valid():

            proveedor=Proveedor()
            proveedor.razon_social=form.cleaned_data["razon_social"]
            proveedor.contacto=form.cleaned_data["contacto"]
            proveedor.correo=form.cleaned_data["correo"]
            proveedor.save()
            messages.success(request, f'Proveedor creado exitosamente.')
            return redirect('proveedor')

        else:
            print('invalido')

    return render(request, 'blogapp/proveedor.html',{'formp':form})

def login(request):
    if request.method == "POST":
        form = LoginForm(data = request.POST)
        
        if form.is_valid():
            usuario=form.cleaned_data["username"]
            clave=form.cleaned_data["password"]
            user=authenticate(request, username=usuario, password=clave)
            if user is not None:
                auth_login(request, user)
                return redirect ('index')
            else:
                messages.error(request,"Nombre o contraseña no válidos.")
                form=LoginForm()
                return render (request, 'blogapp/login.html', {"login_form":form})   
        else:
            messages.error(request,"Nombre o contraseña no válidos.")
            form=LoginForm()
            return render (request, 'blogapp/login.html', {"login_form":form})
    else:
        form=LoginForm()
        return render (request, 'blogapp/login.html', {"login_form":form})

def register(request):
    form = NewUserForm()
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'Usuario {username} creado exitosamente.')
            return redirect('login')
    else:

        form = NewUserForm()
    context = {'form':form}
    return render(request, 'blogapp/register.html', context)

@login_required
def logout_user(request):
	logout(request)
	messages.info(request, "Haz cerrado sesión exitosamente.") 
	return redirect('index')

# def custom_page_not_found_view(request, exception):
#     return render(request, "404.html", {})
    

bootstrap_blog/blogapp/templates/blogapp/includes/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="True">&times;</span>
        </button>
            {{ message }}
    </div>
</div>
{% endfor %}

bootstrap_blog/blogapp/templates/blogapp/index.html
{% extends 'blogapp\layout.html' %}

{% block li%}

{% if user.is_authenticated %}

<li class="nav-item mx-0 mx-lg-1">
  <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'usuarios' %}">Usuarios</a>
</li>
<li class="nav-item mx-0 mx-lg-1">
  <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'proveedor' %}">Proveedores</a>
</li>
<li class="nav-item mx-0 mx-lg-1">
  <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/logout">Salir</a>
</li>
{% else %}
<li class="nav-item mx-0 mx-lg-1">
  <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/login">Iniciar sesión</a>
</li>
<li class="nav-item mx-0 mx-lg-1">
  <a class="nav-link  py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/register">Registrar</a>
</li>

{% endif %}

{% endblock%}

{% block content%}

<!-- Seccion Servicios -->
<section class="page-section portfolio" id="servicios">
  <div class="container">

    <!-- Servicios Section Heading -->
    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Servicios</h2>

    <!-- Icon Divider -->
    <div class="divider-custom">
      <div class="divider-custom-line"></div>
      <div class="divider-custom-icon">
        <i class="fas fa-star"></i>
      </div>
      <div class="divider-custom-line"></div>
    </div>
  </div>
</section>

<!-- Servicios Grid Items -->

  <div class="row">

    <!-- Portfolio Item 1 -->
    <div class="col-md-6 col-lg-4">
      <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal1">
        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
          <div class="portfolio-item-caption-content text-center text-white">
            <i class="fas fa-plus fa-3x"></i>
          </div>
        </div>
        <img class="img-fluid" src="static/img/portfolio/melvin.png" alt="">
      </div>
    </div>

    <!-- Portfolio Item 2 -->
    <div class="col-md-6 col-lg-4">
      <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal2">
        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
          <div class="portfolio-item-caption-content text-center text-white">
            <i class="fas fa-plus fa-3x"></i>
          </div>
        </div>
        <img class="img-fluid" src="static/img/portfolio/formularios.png" alt="">
      </div>
    </div>

    <!-- Portfolio Item 3 -->
    <div class="col-md-6 col-lg-4">
      <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal3">
        <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
          <div class="portfolio-item-caption-content text-center text-white">
            <i class="fas fa-plus fa-3x"></i>
          </div>
        </div>
        <img class="img-fluid" src="static/img/portfolio/ofimatica.png" alt="">
      </div>
    </div>

  </div>
  <br>
  <br>
<!-- /.row -->
<!-- Portfolio Modals -->

<!-- Portfolio Modal 1 -->
<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog"
  aria-labelledby="portfolioModal1Label" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">
          <i class="fas fa-times"></i>
        </span>
      </button>
      <div class="modal-body text-center">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-8">
              <!-- Portfolio Modal - Title -->
              <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Cálculo Asistencia</h2>
              <!-- Icon Divider -->
              <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                  <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
              </div>
              <!-- Portfolio Modal - Image -->
              <img class="img-fluid rounded mb-5" src="static/img/portfolio/melvin.png" alt="">
              <!-- Portfolio Modal - Text -->
              <p class="mb-5">Servicio de </p>
              <button class="btn btn-primary" href="#" data-dismiss="modal">
                <i class="fas fa-times fa-fw"></i>
                Cerrar ventana
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Portfolio Modal 2 -->
<div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog"
  aria-labelledby="portfolioModal2Label" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">
          <i class="fas fa-times"></i>
        </span>
      </button>
      <div class="modal-body text-center">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-8">
              <!-- Portfolio Modal - Title -->
              <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Formularios</h2>
              <!-- Icon Divider -->
              <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                  <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
              </div>
              <!-- Portfolio Modal - Image -->
              <img class="img-fluid rounded mb-5" src="static/img/portfolio/formularios.png" alt="">
              <!-- Portfolio Modal - Text -->
              <p class="mb-5">Confección y envío de formularios</p>
              <button class="btn btn-primary" href="#" data-dismiss="modal">
                <i class="fas fa-times fa-fw"></i>
                Cerrar ventana
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Portfolio Modal 3 -->
<div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog"
  aria-labelledby="portfolioModal3Label" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">
          <i class="fas fa-times"></i>
        </span>
      </button>
      <div class="modal-body text-center">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-8">
              <!-- Portfolio Modal - Title -->
              <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Ofimática</h2>
              <!-- Icon Divider -->
              <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                  <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
              </div>
              <!-- Portfolio Modal - Image -->
              <img class="img-fluid rounded mb-5" src="static/img/portfolio/ofimatica.png" alt="">
              <!-- Portfolio Modal - Text -->
              <p class="mb-5">Ofimática</p>
              <button class="btn btn-primary" href="#" data-dismiss="modal">
                <i class="fas fa-times fa-fw"></i>
                Cerrar ventana
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

bootstrap_blog/blogapp/templates/blogapp/ingreso.html
{% extends 'blogapp/layout.html' %}
<!-- {% load static %} -->

{% block li%}

  <li class="nav-item mx-0 mx-lg-1">
    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'index' %}">Inicio</a>
  </li>
  
{% endblock%} 

{% block content %}


<!-- {% load crispy_forms_tags %} -->

  <!-- Seccion Contacto -->
  <section class="page-section" id="contacto2">
    <div class="container">

      <!-- Contact Section Heading -->
      <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Ingreso de Clientes</h2>

      <!-- Icon Divider -->
      <div class="divider-custom">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon">
          <i class="fas fa-star"></i>
        </div>
        <div class="divider-custom-line"></div>
      </div>

      <!-- Contacto Section Form -->
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
          <form action "blogapp/ingreso.html" method="post">
            {% csrf_token %}
            <div class="control-group">
              <div class="form-group floating-label-form-group controls mb-0 pb-2">
                <label>Nombre</label>
                <input name="{{form.nombre.name}}" class="form-control" id="id_nombre" type="text" placeholder="Nombre" required="required" data-validation-required-message="Favor ingresar datos">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls mb-0 pb-2">
                <label>Apellido</label>
                <input name="{{form.apellido.name}}" class="form-control" id="id_apellido" type="text" placeholder="Apellido" required="required" data-validation-required-message="Favor ingresar datos">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls mb-0 pb-2">
                <label>ApellidoM</label>
                <input name="{{form.apellidoM.name}}" class="form-control" id="id_apellidoM" type="text" placeholder="ApellidoM" required="required" data-validation-required-message="Favor ingresar datos">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls mb-0 pb-2">
                <label>Email</label>
                <input name="{{form.correo.name}}" class="form-control" id="id_correo" type="email" placeholder="Email" required="required" data-validation-required-message="Favor ingresar datos">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls mb-0 pb-2">
                <label>Pais</label>
                <input name="{{form.pais.name}}" class="form-control" id="id_pais" type="text" placeholder="Pais" required="required" data-validation-required-message="Favor ingresar datos">
                <p class="help-block text-danger"></p>
              </div>
            </div>           
            <br>
            <div id="success"></div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-xl">Enviar</button>
            </div>
          </form>
        </div>
      </div>

    </div>
  </section>

  {% endblock %}

bootstrap_blog/blogapp/templates/blogapp/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>TLV</title>

  <!-- Custom fonts for this theme -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap5.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap5.min.js">

  <!-- Theme CSS -->
  <link href="{% static 'css/freelancer.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">Te lo Vendo
        {% if user.is_authenticated %}
       <br>
       Bienvenido, {{user.username}}
      </a>
        {% endif %}
      </a>
      
      <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
      
        {% block li%}

        {% endblock %}
        
        </ul>
      </div>
    </div>
  </nav>

  <!-- Masthead -->
  <header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">

      <!-- Masthead Avatar Image /preguntar como adaptar el alto o poner imagen de fondo --> 
      <!-- <img class="masthead-avatar mb-5" src="{% static 'img/dumi.jpeg' %}" alt=""> -->

      <!-- Masthead Heading -->
      <h1 class="masthead-heading text-uppercase mb-0">Te lo Vendo</h1>
      {% include 'blogapp/includes/messages.html' %}
      <!-- Icon Divider -->
      <div class="divider-custom divider-light">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon">
          <i class="fas fa-star"></i>
        </div>
        <div class="divider-custom-line"></div>
      </div>

      <!-- Masthead Subheading -->
      <p class="masthead-subheading font-weight-light mb-0">Servicios - Formularios - Ofimática</p>

    </div>
  </header>

  {% block content%}

  {% endblock %}

  

  <!-- Footer -->
  <footer class="footer text-center">
    <div class="container">
      <div class="row">

        <!-- Footer Location -->
        <div class="col-lg-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4">Putaendo</h4>
          <p class="lead mb-0">Rinconada de Silva, San Felipe
            <br>Chile</p>
        </div>

        <!-- Footer Social Icons -->
        <div class="col-lg-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4">Redes Sociales</h4>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-facebook-f"></i>
          </a>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-twitter"></i>
          </a>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-linkedin-in"></i>
          </a>
          <a class="btn btn-outline-light btn-social mx-1" href="#">
            <i class="fab fa-fw fa-dribbble"></i>
          </a>
        </div>

        <!-- Footer About Text -->
        <div class="col-lg-4">
          <h4 class="text-uppercase mb-4">Alumna</h4>
          <p class="lead mb-0">Patricia Olivares Delgado</p>
        </div>

      </div>
    </div>
  </footer>

  <!-- Copyright Section -->
  <section class="copyright py-4 text-center text-white">
    <div class="container">
      <small>Copyright &copy; 2022</small>
    </div>
  </section>

  <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
  <div class="scroll-to-top d-lg-none position-fixed ">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
      <i class="fa fa-chevron-up"></i>
    </a>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Contact Form JavaScript -->
  <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
  <script src="{% static 'js/contact_me.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/freelancer.min.js' %}"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

bootstrap_blog/blogapp/templates/blogapp/login.html
{% extends 'blogapp/layout.html' %}
{% block li%}

  <li class="nav-item mx-0 mx-lg-1">
    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'index' %}">Inicio</a>
  </li>
 
{% endblock%} 

{% block content %}
{% load static %}

{% load crispy_forms_tags %}

<div class="container py-5">
    
	<h3>Iniciar sesión</h3>
    <br>
	<form method="post">

        {% csrf_token %}

        {{login_form|crispy}}
        <input class="btn btn-primary" type="submit" value="Enviar" />
    </form>
</div>

{% endblock %}

bootstrap_blog/blogapp/templates/blogapp/proveedor.html
{% extends 'blogapp/layout.html' %}
{% block li%}

  <li class="nav-item mx-0 mx-lg-1">
    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'index' %}">Inicio</a>
  </li>
 
{% endblock%} 

{% block content %}
<!-- {% load static %} -->

{% load crispy_forms_tags %}

<form action "blogapp/proveedor.html" method="post">

  {% csrf_token %}
  <h1> Ingreso de Proveedores </h1>

  {{formp|crispy}}

  <input type="submit"></input>

</form>


{% endblock %}

bootstrap_blog/blogapp/templates/blogapp/register.html
{% extends 'blogapp\layout.html' %}

{% block li%}

<li class="nav-item mx-0 mx-lg-1">
  <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'index' %}">Inicio</a>
</li>

{% endblock%}

{% block content%}
{% load crispy_forms_tags %}
<div class="container py-5">

  <h3>Crear cuenta</h3>
  <br>
  <form method="post">

    {% csrf_token %}

    {{form|crispy}}
    <input class="btn btn-primary" type="submit" value="Enviar" />
  </form>
</div>
{% endblock %}

bootstrap_blog/blogapp/templates/blogapp/usuarios.html
{% extends 'blogapp\layout.html' %}

{% block li%}

  <li class="nav-item mx-0 mx-lg-1">
    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'index' %}">Inicio</a>
  </li>
  <li class="nav-item mx-0 mx-lg-1">
    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#lista_usuario">Usuarios</a>
  </li>
  <li class="nav-item mx-0 mx-lg-1">
    <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'ingreso' %}">Ingresar Cliente</a>
  </li>
  
  
{% endblock%} 


{% block content%}

<!-- Seccion Lista de Usuarios -->
<section class="page-section" id="lista_usuario">
    <div class="container">

        <!-- Contact Section Heading -->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Listado Usuarios</h2>

        <!-- Icon Divider -->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>
        <div class="table-responsive">
            <table class="table">
                <tr class="bg-primary">
                    <th scope="col" >Nombre</th>
                    <th scope="col" >Apellido Paterno</th>
                    <th scope="col" >Apellido Materno</th>
                    <th scope="col" >Correo</th>
                    <th scope="col" >Pais</th>
                </tr>
                {% for cli in data %}
                <tr>
                    <td class="bg-primary">{{cli.nombre}}</td>
                    <td class="bg-primary">{{cli.apellido}}</td>
                    <td class="bg-primary">{{cli.apellidoM}}</td>
                    <td class="bg-primary">{{cli.correo}}</td>
                    <td class="bg-primary">{{cli.pais}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</section>






{% endblock %}